Ingredient.create(name: "rootbeer")
Ingredient.create(name: "mezcal")
Ingredient.create(name: "absinthe")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "olives")
Ingredient.create(name: "martini")
Ingredient.create(name: "gin")

Cocktail.create!(name: "Lulu White")
Cocktail.create!(name: "Dark & Stormy")
Cocktail.create!(name: "Dirty Martini")
